### ISSUE TITLE
GtkMenuAdapter is missing contextMenu implementations:

### ISSUE THREAD

**Issue by pavel-krivanek** [pharo-spec/mars-gtk#2]
The GtkMenuAdapter is missing the method adaptAsPopup: which means that custom context menus cannot be done in the GTK.

**Comment by estebanlm** [comment]
Not really. 
In Spec2 is not preview that a popup can be shown arbitrary at any place any moment.
Context menus in Spec2 are made using `contextMenu` entries in the widgets that supports it. 

And yes, there are missing contextMenu implementations, but not the `#adaptAsPopup:` message.

(not closing this issue to allow further discussion)

**Comment by pavel-krivanek** [comment]
ok ;-)

**Comment by estebanlm** [comment]
this is fixed upstream
