### ISSUE TITLE
SpWindowResizing did not understand #newSize:

### ISSUE THREAD

**Issue by BrendanLandais** [pharo-spec/mars-gtk#43]
It seems recent update on GtkWindowAdapter cause trouble. 

Context:
OS: Windows 10.
VM: http://files.pharo.org/vm/pharo-spur64-headless/win/latest-win64-GTK.zip
Pharo 8.0.0
Build information: Pharo-8.0.0+build.1134.sha.5173b0271894727189f261cb9eb9beaa3db3f205 (64 Bit)
Image: https://get.pharo.org/64/80

I load Mars-GTK package:
Metacello new 
	repository: 'github://pharo-spec/mars-gtk';
	baseline: 'Mars';
	load.
Metacello new 
	repository: 'github://pharo-nosql/voyage';
	baseline: 'Voyage';
	load: 'memory'.

I create DemoApplication, following the TechTalk 'Working with Spec2 and GTK' (https://www.youtube.com/watch?v=IVY7TH4MCXI&list=PL4actYd6bfnx8l8cqYWhdNB6gJgRvk5sH)

Then i try to launch the application, by executing:
	app := DemoApplication new.
	(app new: DemoFilmListPresenter) openWithSpec.

Freeze Of Pharo Image - I have to kill Pharo Virtual Machine using Task Manager of Windows 10.

stderr file explains error:
[31mInstance of SpWindowResizing did not understand #newSize:
[0mSpWindowResizing(Object)>>doesNotUnderstand: #newSize:
GtkWindowAdapter>>announceResized:

It works fine if I go back on this modification to use WindowResizing instead.

**Comment by pavel-krivanek** [comment]
ok, thanks for the report. SpWindowResizing is Morphic independent copy of WindowResizing, we need to make the API of this class more compatible.

**Comment by pavel-krivanek** [comment]
it should be fixed in the new commits of Spec2. Can you, please, test it?

**Comment by BrendanLandais** [comment]
Yes, it's fixed now.
Well done, thank you.
