### ISSUE TITLE
How to start the UI?

### ISSUE THREAD

**Issue by bergel** [pharo-spec/mars-gtk#44]
Hi!

I am not sure how to launch the UI. I did the following:
```
brew install gtk+3
curl https://get.pharo.org/64/80+vmHeadlessLatest | bash
./pharo-ui Pharo.image    
```

Then I executed:
```Smalltalk
Metacello new
        repository: 'github://pharo-spec/mars-gtk';
        baseline: 'Mars';
        onConflict: [ :e | e useIncoming ];
        onUpgrade: [ :e | e useIncoming ];
        ignoreImage;
        load
```

I then saved the image. 

But I am not sure what I should do next?

**Comment by estebanlm** [comment]
just restart, it should work.

**Comment by bergel** [comment]
No, it does not work :-(
Should I run `pharo-ui`? or simply `pharo`? In any case, running `pharo Pharo.image` does not seems to run the image at all.

How can I have a gtk-based playground and code browser ? 👍

**Comment by estebanlm** [comment]
what does not works?
pharo-ui after installed mars-gtk and the gtk backend, should start automatically in gtk backend.
if this does not, please ping me at discord, we will figure out what is happening.

**Comment by estebanlm** [comment]
this was solved (Alex was starting the UI, just he didn't realise it because he was expecting something different and mind-blowing... which is not yet there ;)
